name: Test => Build => Push

on:
  push:
    branches: [main]
  pull_request:

env:
  DOCKER_IMAGE: ghcr.io/${{ github.event.repository }}
  DOCKER_TAG  : ${{ github.ref_name }}-${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ github.event.repository.owner.login }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ghcr.io
        name: Docker login

      - run: docker info
        name: Docker Info

      - run: docker build -t ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }} .
        name: Build

      - run: docker push ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
        name: Push

































    # test:
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-python@v5.5.0
  #       with:
  #         python-version: "3.12.3"
  #         cache: "pip"
  #         cache-dependency-path: "app/requirements.txt"
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -r app/requirements.txt
  #     - run: pytest app/tests/