name: Test => Build => Push

on:
  push:
    branches: [main]
  pull_request:

env:
  DOCKER_TAG  : ${{ github.ref_name }}-${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build & Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ${{ github.event.repository.name }}
          tags: ${{ env.DOCKER_TAG }}
          registry: ghcr.io
          dockerfile: Dockerfile
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

































    # test:
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-python@v5.5.0
  #       with:
  #         python-version: "3.12.3"
  #         cache: "pip"
  #         cache-dependency-path: "app/requirements.txt"
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -r app/requirements.txt
  #     - run: pytest app/tests/